---

- hosts: nodes

  become: true

  vars_files:
      - role.yml

  tasks:
    - name: Install OpenLDAP (RHEL-based)
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - openldap
        - openldap-servers
      when: ansible_os_family == "RedHat"

    - name: Preseed OpenLDAP password1 (Debian-based)
      debconf:
              name: slapd
              question: slapd/password1
              value: root
              vtype: password
      when: ansible_os_family == "Debian"

    - name: Preseed OpenLDAP password2 (Debian-based)
      debconf:
              name: slapd
              question: slapd/password2
              value: root
              vtype: password
      when: ansible_os_family == "Debian"

    - name: Install OpenLDAP (Debian-based)
      debconf:
              name: slapd
              question: slapd/internal/generated_adminpw
              value: root
              vtype: password
      when: ansible_os_family == "Debian"
    
    - name: Enable and start OpenLDAP
      systemd:
        state: started
        enabled: yes
        name: slapd

    - name: Copy LDAP ldifs to host
      copy:
        src: ldap/ldaprootpasswd.ldif
        dest: /tmp/ldaprootpasswd.ldif
        owner: root
        group: root
        mode: '0600'
        force: yes
      template:
        src: ldap/ldapgroup-systemusers.ldif.j2
        dest: /tmp/ldapgroup-systemusers.ldif
        owner: root
        group: root
        mode: '0600'
        force: yes
      template:
        src: ldap/ldapgroup-platformusers.ldif.j2
        dest: /tmp/ldapgroup-platformusers.ldif
        owner: root
        group: root
        mode: '0600'
        force: yes
      template:
        src: ldap/ldapdomain.ldif.j2
        dest: /tmp/ldapdomain.ldif
        owner: root
        group: root
        mode: '0600'
        force: yes
      template:
        src: ldap/base_ldap_domain.ldif.j2
        dest: /tmp/baseldapdomain.ldif
        owner: root
        group: root
        mode: '0600'
        force: yes

    - name: Import ldifs to LDAP
      shell: |
        ldapadd -Y EXTERNAL -H ldapi:/// -f /tmp/ldaprootpasswd.ldif 
        cp /usr/share/openldap-servers/DB_CONFIG.example /var/lib/ldap/DB_CONFIG
        chown -R ldap:ldap /var/lib/ldap/DB_CONFIG
        systemctl restart slapd
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/cosine.ldif 
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/nis.ldif
        ldapadd -Y EXTERNAL -H ldapi:/// -f /etc/openldap/schema/inetorgperson.ldif
        ldapmodify -Y EXTERNAL -H ldapi:/// -f /tmp/ldapdomain.ldif
        ldapadd -Y EXTERNAL -x -D cn=SystemUsers,dc={{ldap_base_domain}},dc={{ldap_base_ext}} -W -f baseldapdomain.ldif
        groupadd -r -g 1518 systemusers
        groupadd -r -g 1511 platformusers
        ldapadd -Y EXTERNAL -x  -W -D "cn=SystemUsers,dc={{ldap_base_domain}},dc={{ldap_base_ext}}" -f ldapgroup-systemusers.ldif
        ldapadd -Y EXTERNAL -x  -W -D "cn=PlatformUsers,dc={{ldap_base_domain}},dc={{ldap_base_ext}}" -f ldapgroup-platformusers.ldif